# Generated by Django 4.0.3 on 2022-04-21 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishType', models.CharField(max_length=30)),
                ('fishAmount', models.CharField(max_length=30)),
                ('notes', models.CharField(max_length=200)),
                ('tankId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
