# Generated by Django 4.0.3 on 2022-04-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fish',
            old_name='tankId',
            new_name='tankName',
        ),
    ]
