# Generated by Django 4.0.3 on 2022-04-08 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MxManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodSchedule', models.CharField(max_length=30)),
                ('waterTempCheck', models.CharField(max_length=30)),
                ('waterChange', models.CharField(max_length=30)),
                ('plantCare', models.CharField(max_length=100)),
                ('scheduleNotes', models.CharField(max_length=100)),
                ('mxManagerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
