# Generated by Django 4.0.3 on 2022-04-27 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField(max_length=30)),
                ('water_type', models.CharField(max_length=30)),
                ('tank_size', models.IntegerField()),
                ('water_temp_chk_last_done', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('next_temp_chk_due', models.CharField(max_length=30)),
                ('water_change_last_done', models.CharField(max_length=30)),
                ('amount_percent', models.CharField(max_length=30)),
                ('next_water_change_due', models.CharField(max_length=30)),
                ('plant_care_last_done', models.CharField(max_length=30)),
                ('next_plant_chk_due', models.CharField(max_length=30)),
                ('water_levels_chk_last_done', models.CharField(max_length=30, null=True)),
                ('ph_level', models.CharField(max_length=30)),
                ('nitrite_level', models.CharField(max_length=30)),
                ('nitrate_level', models.CharField(max_length=30)),
                ('o2_level', models.CharField(max_length=30)),
                ('next_levels_chk_due', models.CharField(max_length=30)),
                ('tank_notes', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
