# Generated by Django 4.0.3 on 2022-04-08 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tankName', models.CharField(max_length=30)),
                ('waterType', models.CharField(max_length=30)),
                ('tankSize', models.IntegerField()),
                ('fishType', models.CharField(max_length=100)),
                ('fishAmount', models.IntegerField()),
                ('plantType', models.CharField(max_length=100)),
                ('plantAmount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
