# Generated by Django 4.0.3 on 2022-04-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='tank_size',
            field=models.CharField(max_length=30),
        ),
    ]
